import re
from .textast import Node, VSpace, CList, lazy, Ast
from collections import OrderedDict

class Ident(Node):
    __slots__ = OrderedDict([
        ('value', str),
        ])
    re_ident = re.compile('^[a-zA-Z_][0-9a-zA-Z_]*$')
    def __init__(self, value):
        assert self.re_ident.match(value)
        self.value = value

class Typename(Node):
    __slots__ = OrderedDict([
        ('value', str),
        ])
    re_typename = re.compile('''^
        (?:(?:const|static)\s+)?
        (?:(?:unsigned|signed)\s+)?
        (?:char|short|int|long|bool|float|double|\w+_t)
        \s*(?:\*\s*)* |
        struct\s+\w+
        $''', re.X)
    def __init__(self, value):
        assert self.re_typename.match(value)
        self.value = value

class CommentBlock(Node):
    __slots__ = OrderedDict([
        ('lines', str),
        ])
    top = True
    each_line = '/* {0:s} */'

    def __init__(self, *lines):
        self.lines = lines

class StdInclude(Node):
    __slots__ = OrderedDict([
        ('filename', str),
        ])
    top = True
    line_format = '#include <{filename:s}>'

class Var(Node):
    __slots__ = OrderedDict([
        ('type', (Typename, lazy.Struct)),
        ('name', Ident),
        ])
    top = True
    line_format = '{type} {name};'

class Struct(Node):
    __slots__ = OrderedDict([
        ('name', Ident),
        ('body', CList(Var)),
        ])
    top = True
    block_start = 'struct {name} {{'
    block_end = '}}'

class TypeDef(Node):
    __slots__ = OrderedDict([
        ('definition', (Typename, Struct)),
        ('name', Ident),
        ])
    top = True
    line_format = 'typedef {definition} {name};'

lazy.fix(globals())

if __name__ == '__main__':
    def sample(ast):
        ast(CommentBlock(
            "THIS IS AUTOGENERATED FILE",
            "DO NOT EDIT!!!",
            ))
        ast(StdInclude('coyaml_hdr.h'))
        ast(VSpace())
        with ast.body(Struct('test_s')) as st:
            ast(Var(Typename('int'), 'intval'))
            ast(Var(Typename('unsigned long'), 'longval'))
            ast(Var(Typename('const char *'), 'stringval'))
        ast(TypeDef(st, 'test_t'))
    print(str(Ast(sample)))
